# Fuzzel Colors
# Beans (Helix), mapped from the Alacritty theme

[colors]
background=111111cc
text=ebebd8ff
prompt=be67e1ff
placeholder=6d6d6dff
input=48c6ffff
match=ccff00ff
selection=be67e1ff
selection-text=1c1c1cff
selection-match=ccff00ff
counter=be67e1ff
border=48c6ffff
